# permissions for end users to edit statefulsingletons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statefulsingleton-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stateful-singleton
    app.kubernetes.io/part-of: stateful-singleton
    app.kubernetes.io/managed-by: kustomize
  name: statefulsingleton-editor-role
rules:
- apiGroups:
  - apps.statefulsingleton.com
  resources:
  - statefulsingletons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.statefulsingleton.com
  resources:
  - statefulsingletons/status
  verbs:
  - get
