apiVersion: apps.openshift.yourdomain.com/v1
kind: StatefulSingleton
metadata:
  name: sample-database
spec:
  selector:
    matchLabels:
      app: postgres-database
  terminationGracePeriod: 120  # 2 minutes
  maxTransitionTime: 300       # 5 minutes total transition timeout
  respectPodGracePeriod: true  # Use pod's grace period if longer