apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  annotations:
    # OpenShift service serving certificate annotation
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert